### ISSUE TITLE
"Boxer is damaged" alert when opening Apple Silicon beta release

### ISSUE THREAD

**Issue by JoshHrach** [MaddTheSane/Boxer#35] opened 2021-11-13 00:35 UTC
When attempting to open the Apple Silicon beta:

> “Boxer” is damaged and can’t be opened. You should move it to the Trash.

More info on the alert mentions:

> The app has been modified, and its code does not match the original signed code.

**Comment by kcgen** [comment] 2021-11-13 05:01
This fork uses DOSBox Staging under the hood, which itself tracks DOSBox proper. 
When @MaddTheSane can rebase against the latest code, then Boxer should be working again. 
My understanding is that DOSBox-X also works great on macOS, as does DOSBox (proper), which should work with Rosetta and x86. I'm not sure if DOSBox ECE has macOS builds - but the x86 binary should also be good under Rosetta. Hope any of these help you get up and running in the meantime, until Boxer is resync'd! 
(@MaddTheSane -- feel free to delete this post when Boxer's sync'd up and running again on macOS m1.)

**Comment by MaddTheSane** [comment] 2021-11-13 07:59
You shouldn't be getting that error…

**Comment by shinra-electric** [comment] 2021-11-13 15:18
I get it too.  

On an M1 Pro, Monterey 12.0.1

The "App is modified" bit is just if you go into the help, and is a generic message (I'd say).

![Screenshot 2021-11-13 at 15 17 24](https://user-images.githubusercontent.com/50119606/141649164-36918e00-7813-40c3-b589-9932963ccd70.png)

Edit: It's probably an issue with code signing and/or notarisation...?

**Comment by JoshHrach** [comment] 2021-11-13 17:05
> The "App is modified" bit is just if you go into the help, and is a generic message (I'd say).

I would agree. It's likely generic. I just wish I had more info to share from the alert itself.

**Comment by BergQuester** [comment] 2021-11-20 17:46
I get the same here.

M1 Max, macOS 12.0.1

**Comment by designbyadrian** [comment] 2021-12-07 14:15
M1 Pro, macOS 12.0.1

**Comment by ajmas** [comment] 2021-12-07 15:06
Which version and which is the download link you are using?

**Comment by shinra-electric** [comment] 2021-12-07 15:14
For myself, I'm downloading Boxer.zip from the [releases](https://github.com/MaddTheSane/Boxer/releases) page. 

I see there is a new beta 2 release posted last week, but I get the same damaged error.

**Comment by ajmas** [comment] 2021-12-07 15:22
Are you seeing anything in the /var/log/system.log , during the failure, that might seem relevant?

**Comment by BergQuester** [comment] 2021-12-07 15:31
> For myself, I'm downloading Boxer.zip from the [releases](https://github.com/MaddTheSane/Boxer/releases) page.
> 
> I see there is a new beta 2 release posted last week, but I get the same damaged error.

Same here.

**Comment by shinra-electric** [comment] 2021-12-07 16:33
Nope, nothing shows up in the log when I attempt to open. 

(I'm looking at the system.log in the console app)

**Comment by ajmas** [comment] 2021-12-07 19:40
Does anything here work: https://osxdaily.com/2019/02/13/fix-app-damaged-cant-be-opened-trash-error-mac/

**Comment by shinra-electric** [comment] 2021-12-07 23:03
Stripping the attributes with xattr probably works, but that is a workaround and not a fix. 

There is an issue with either the signing or the notarisation of the release builds, and fixing that means using xattr won’t be necessary.

**Comment by MaddTheSane** [comment] 2021-12-07 23:06
It is most likely due to me not having a paid developer account.

I'll look into getting a paid account next year.

**Comment by shinra-electric** [comment] 2021-12-07 23:10
As far as I’m aware, free accounts should work too. I read something about it recently. I’ll try to find where it was….

**Comment by ajmas** [comment] 2021-12-07 23:54
> Stripping the attributes with xattr probably works, but that is a workaround and not a fix.
> 
> There is an issue with either the signing or the notarisation of the release builds, and fixing that means using xattr won’t be necessary.

I wasn’t suggesting these were ideal fixes, but if one of these worked it would give a better clue to what’s going on.

**Comment by ajmas** [comment] 2021-12-08 20:16
I can confirm it is a code signing issue, based on the report produced by [Apparency](https://mothersruin.com/software/Apparency/):

<img width="1141" alt="Screenshot 2021-12-08 at 15 15 40" src="https://user-images.githubusercontent.com/682269/145278045-69b9e01d-9d3e-4795-b563-67f0b7205934.png">

**Comment by shinra-electric** [comment] 2021-12-08 23:16
Does it say what the reason for rejection was?

I was unfortunately unable to find the explanation I mentioned above, but from (hazy) memory it was something like: you can codesign with a free dev account, but you need to be careful that no modifications are done to the files in any steps after, or else you’ll get the “damaged” warning. Notarisation is only to get rid of the “possible malware” warning that can be gotten around by opening from the context menu (twice). 

I could be misremembering though…

**Comment by shinra-electric** [comment] 2021-12-08 23:45
By the way, the guy who posted issue #9 sounds like a person we should ask…

**Comment by ajmas** [comment] 2021-12-09 15:24
It didn't give more details on why Gatekeeper rejected, but this thread may provide some ideas of what to investigate:

[Successfully notarized app rejected by gatekeeper
](https://developer.apple.com/forums/thread/128038)

Also, the developers of Apparency have a [table](https://www.mothersruin.com/software/Apparency/faq.html?utm_source=signature-status-help&utm_medium=apparency-app#gatekeeper-status), with an explanation:

> The app or component was signed with a certificate that is not trusted by Gatekeeper (or perhaps not even by macOS; see below). This might be case the if the component was signed with a third-party certificate (which would be uncommon) or perhaps with an Apple-issued certificate that is not of the Developer ID variety (such as an App Store distribution certificate, which is only supposed to be used for submission to Apple, but is sometimes mistakenly used elsewhere).

**Comment by MaddTheSane** [comment] 2021-12-09 20:09
I found out why: The hidapi framework inside SDL2 expected its header to be in it.
But headers are stripped.

New build coming soon.

**Comment by MaddTheSane** [comment] 2021-12-09 20:17
New build [released](https://github.com/MaddTheSane/Boxer/releases/tag/AS-beta-3).

Closing.

**Closed as completed by MaddTheSane** 2021-12-09 20:17 UTC

**Comment by angstsmurf** [comment] 2022-03-26 18:33
I still get this with the latest release. Right clicking > Open or `xattr -cr` won't help.
